/* EFV-panel — settings defaults.
   Values derived from BPB-Worker-Panel (GPL-3.0) defaults, trimmed to the
   EFV contract in types/settings.ts. Generated mechanically — edit carefully. */

import { KvSettings } from '#types/settings';

export const DEFAULT_KV_SETTINGS: KvSettings = {
    localDNS: "8.8.8.8",
    antiSanctionDNS: "178.22.122.100",
    fakeDNS: false,
    enableIPv6: false,
    allowLANConnection: false,
    logLevel: "warning",
    customDomain: "",
    remoteDNS: "https://8.8.8.8/dns-query",
    remoteDnsHost: {
        isDomain: false,
        host: "8.8.8.8",
        ipv4: [],
        ipv6: []
    },
    upstreamProxy: "",
    upstreamParams: {
        upstreamServer: "",
        upstreamPort: 0
    },
    chainProxy: "",
    chainProxyParams: {

    },
    cleanIPs: ["www.speedtest.net"],
    customCdnAddrs: [],
    customCdnHost: "",
    customCdnSni: "",
    bestPingInterval: 30,
    protocols: "vless,trojan",
    ports: [443],
    fingerprint: "chrome",
    enableTFO: false,
    fragmentMode: "custom",
    fragmentLengthMin: 100,
    fragmentLengthMax: 200,
    fragmentDelayMin: 1,
    fragmentDelayMax: 1,
    fragmentPackets: "tlshello",
    fragmentMaxSplitMin: 0,
    fragmentMaxSplitMax: 0,
    enableECH: false,
    echServerName: "",
    bypassIran: false,
    bypassChina: false,
    bypassRussia: false,
    bypassOpenAi: false,
    bypassGoogleAi: false,
    bypassMicrosoft: false,
    bypassOracle: false,
    bypassDocker: false,
    bypassAdobe: false,
    bypassEpicGames: false,
    bypassIntel: false,
    bypassAmd: false,
    bypassNvidia: false,
    bypassAsus: false,
    bypassHp: false,
    bypassLenovo: false,
    blockAds: false,
    blockPorn: false,
    blockUDP443: false,
    blockMalware: false,
    blockPhishing: false,
    blockCryptominers: false,
    customBypassRules: [],
    customBlockRules: [],
    customBypassSanctionRules: [],
    warpRemoteDNS: "1.1.1.1",
    warpEndpoints: ["engage.cloudflareclient.com:2408"],
    warpBestPingInterval: 30,
    warpReservedBytes: true,
    xrayUdpNoises: [
        {
            type: 'rand',
            packet: '50-100',
            delay: '1-5',
            count: 5
        }
    ],
    knockerNoiseMode: 'quic',
    knockerNoiseCountMin: 10,
    knockerNoiseCountMax: 15,
    knockerNoiseSizeMin: 5,
    knockerNoiseSizeMax: 10,
    knockerNoiseDelayMin: 1,
    knockerNoiseDelayMax: 1,
    amneziaNoiseCount: 5,
    amneziaNoiseSizeMin: 50,
    amneziaNoiseSizeMax: 100,
    customSubs: [],
    customConfigs: [],
    remoteSettings: "",
    panelVersion: "1.0.0",
};
